###############################################################################
# Cloud SQL for PostgreSQL — persistence for the self-hosted Temporal server.
# Per ARCHITECTURE.md §12.6.1:
#   - POSTGRES_15
#   - tier from var.tier; disk_size from var.disk_gb (autoresize on)
#   - availability_type: ZONAL for stage, REGIONAL for prod
#   - private IP only (ipv4_enabled = false); peered via Private Service Access
#   - Two databases: temporal, temporal_visibility
#   - Postgres user `temporal` with password generated by random_password and
#     stored in Secret Manager as `temporal-postgres-password`
#
# Apply order: this module depends on the networking module's
# google_service_networking_connection (passed in as var.psa_dependency) — the
# PSA peering must exist before the SQL instance can be created with a private IP.
###############################################################################

locals {
  instance_name = "${var.app_name}-temporal-${var.environment}"
  common_labels = merge(
    {
      app     = var.app_name
      env     = var.environment
      purpose = "temporal-persistence"
    },
    var.labels,
  )
}

# Strong random password for the postgres `temporal` user. The result is the
# only place this value exists outside Secret Manager — and `result` is marked
# sensitive by the provider, so it never appears in plan/apply output.
resource "random_password" "postgres" {
  length      = 32
  special     = true
  min_lower   = 4
  min_upper   = 4
  min_numeric = 4
  min_special = 2
  # Avoid characters that may need URL/shell escaping when consumed via env var.
  override_special = "!@#$%^&*()-_=+[]{}<>?"
}

# Secret Manager — the durable home for the password. The temporal-server
# Cloud Run service mounts this via secret reference; nothing else reads it.
# Lives in cloud_sql because the password's lifecycle is owned by the SQL user;
# the secret_manager module (§8) handles other secrets (hf-token, wandb-api-key, …).
resource "google_secret_manager_secret" "postgres_password" {
  project   = var.project_id
  secret_id = "temporal-postgres-password"

  replication {
    auto {}
  }

  labels = local.common_labels
}

resource "google_secret_manager_secret_version" "postgres_password" {
  secret      = google_secret_manager_secret.postgres_password.id
  secret_data = random_password.postgres.result

  # Recreate the secret version when the password rotates, so a new fingerprint
  # forces the Cloud Run service to roll.
  lifecycle {
    create_before_destroy = true
  }
}

# The SQL instance itself.
resource "google_sql_database_instance" "temporal" {
  project          = var.project_id
  name             = local.instance_name
  region           = var.region
  database_version = "POSTGRES_15"

  # Don't keep prod data hostage to a stack delete — but keep it on by default.
  deletion_protection = var.deletion_protection

  settings {
    tier = var.tier
    # ZONAL for stage (cheap), REGIONAL for prod (HA failover).
    availability_type = var.environment == "prod" ? "REGIONAL" : "ZONAL"

    disk_size       = var.disk_gb
    disk_autoresize = true
    disk_type       = "PD_SSD"

    backup_configuration {
      enabled                        = true
      point_in_time_recovery_enabled = true
      transaction_log_retention_days = 7
      backup_retention_settings {
        retained_backups = 7
      }
    }

    # Private IP only — no public access. ipv4_enabled = false enforces that.
    ip_configuration {
      ipv4_enabled    = false
      private_network = var.network_id
      ssl_mode        = "ENCRYPTED_ONLY"
    }

    # Spread maintenance windows so stage and prod don't restart at the same hour.
    maintenance_window {
      day          = var.environment == "prod" ? 7 : 6 # Sun for prod, Sat for stage
      hour         = 3                                 # 03:00 in the instance's region
      update_track = "stable"
    }

    insights_config {
      query_insights_enabled  = true
      record_application_tags = false
      record_client_address   = false
    }

    user_labels = local.common_labels
  }

  # Forces the PSA peering to be in place before the instance is created.
  # Without this, the apply fails with "service networking connection does not exist".
  depends_on = [var.psa_dependency]
}

# Application databases consumed by temporalio/auto-setup (DBNAME and
# VISIBILITY_DBNAME env vars in §12.6.2).
resource "google_sql_database" "temporal" {
  project  = var.project_id
  instance = google_sql_database_instance.temporal.name
  name     = "temporal"
}

resource "google_sql_database" "temporal_visibility" {
  project  = var.project_id
  instance = google_sql_database_instance.temporal.name
  name     = "temporal_visibility"
}

# The `temporal` postgres user; auto-setup connects as this principal.
resource "google_sql_user" "temporal" {
  project  = var.project_id
  instance = google_sql_database_instance.temporal.name
  name     = "temporal"
  password = random_password.postgres.result
}
